# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/kiemtra?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# THYMELEAF CONFIG
# Tat cache de khi sua HTML trinh duyet cap nhat ngay
spring.thymeleaf.cache=false